#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'base',
  :path => 'site-cookbooks/base'

cookbook 'bitlbee',
  :path => 'site-cookbooks/bitlbee'

cookbook 'docker',
  :path => 'site-cookbooks/docker'

cookbook 'irssi',
  :path => 'site-cookbooks/irssi'

cookbook 'letsencrypt',
  :path => 'site-cookbooks/letsencrypt'

cookbook 'tor',
  :path => 'site-cookbooks/tor'

cookbook 'nostalgix_nginx',
  :path => 'site-cookbooks/nostalgix_nginx'

cookbook 'postfix',
  :path => 'site-cookbooks/postfix'

cookbook 'iptables-ng', '~> 3.0.0'
