name 'letsencrypt'
maintainer 'Arvid Warnecke'
maintainer_email 'madhatter@nostalgix.org'
license 'BSD'
description 'Installation of letsencrypt tool'
long_description 'Installs letsencrypt and helper scripts.'
source_url 'https://github.com/madhatter/chef'
issues_url 'https://github.com/madhatter/chef/issues'
version '0.0.1'

supports 'arch'
