name 'tor'
maintainer 'Arvid Warnecke'
maintainer_email 'madhatter@nostalgix.org'
license 'BSD'
description 'Installs/Configures Tor AP'
long_description 'Installs and configures an access point to Tor.'
version '0.0.1'

supports 'arch'
depends 'iptables-ng'
