name 'docker'
maintainer 'Arvid Warnecke'
maintainer_email 'madhatter@nostalgix.org'
license 'BSD'
description 'Installs/configures docker'
long_description 'Installation and configuration of docker and docker related services'
source_url 'https://github.com/madhatter/chef'
issues_url 'https://github.com/madhatter/chef/issues'
version '0.0.1'

supports 'arch'
