name 'nostalgix_nginx'
maintainer 'Arvid Warnecke'
maintainer_email 'madhatter@nostalgix.org'
license 'BSD'
description 'nginx setup for nostalgix.org'
long_description 'Installs and configures nginx for nostalgix.org.'
source_url 'https://github.com/madhatter/chef'
issues_url 'https://github.com/madhatter/chef/issues'
version '0.0.1'

supports 'arch'
