name 'base'
maintainer 'Arvid Warnecke'
maintainer_email 'madhatter@nostalgix.org'
license 'BSD'
description 'Basic node setup'
long_description 'Installs all the base services and users.'
source_url 'https://github.com/madhatter/chef'
issues_url 'https://github.com/madhatter/chef/issues'
version '0.0.1'

supports 'arch'
